AWSTemplateFormatVersion: '2010-09-09'
Description: Tsunmiki Uploader Platform

Parameters:
  CertificateArn:
    Type: String

  ApiCertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  HostedZoneName:
    Type: String
  DomainName:
    Type: String
  ApiDomainName:
    Type: String

Resources:
  #
  # Certifications
  #

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ApiDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  CertDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref ApiDomainName
      RegionalCertificateArn: !Ref ApiCertificate
      EndpointConfiguration:
        Types: [REGIONAL]

  #
  # Servers
  #

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront Distribution
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        Origins:
          - DomainName: "{{resolve:ssm:/app/tsumiki-uploader/platform/storages/frontend/domain-name}}"
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        PriceClass: PriceClass_All

  #
  # Resolve Name
  #

  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}"
      Name: !Sub "${ApiDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt CertDomainName.RegionalDomainName
        HostedZoneId: !GetAtt CertDomainName.RegionalHostedZoneId

  WebDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}"
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # constant
        DNSName: !GetAtt CloudFrontDistribution.DomainName

  #
  # Parameters
  #

  ApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/tsumiki-uploader/platform/api-domain-name
      Type: String
      Value: !Ref CertDomainName

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront Distribution Domain Name
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: CloudFront Distribution ID
