openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Backend
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /storage/transactions:
    post:
      operationId: createTransaction
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Transaction:
      type: object
      required:
        - id
        - url
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
