openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Backend
  license:
    name: MIT
servers:
  - url: http://example.com/v1
paths:
  /storage/files/{key}:
    get:
      operationId: getFileUrl
      parameters:
        - in: path
          name: key
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DownloadInfo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /storage/files/{key}/thumbnails:
    get:
      operationId: getFileThumbnailUrls
      parameters:
        - in: path
          name: key
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileThumbnails"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /transactions/storing_file:
    post:
      operationId: createTransaction
      responses:
        '201':
          description: created transaction info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /transactions/storing_file/{transaction_id}:
    patch:
      operationId: updateTransaction
      parameters:
        - in: path
          name: transaction_id
          description: target transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  $ref: "#/components/schemas/TransactionStatus"
      responses:
        '200':
          description: Updated Transaction
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
components:
  schemas:
    FileThumbnail:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    FileThumbnails:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/FileThumbnail"
    DownloadInfo:
      type: object
      required:
        - name
        - url
        - thumbnails
      properties:
        name:
          type: string
        url:
          type: string
    TransactionStatus:
      type: string
      enum: [READY, UPLOADED]
    Transaction:
      type: object
      required:
        - id
        - status
        - url
      properties:
        id:
          type: string
        status:
          $ref: "#/components/schemas/TransactionStatus"
        url:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
