AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend API to store data

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  Storage:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ["*"]
            AllowedMethods: [GET, PUT]
            AllowedHeaders: ["*"]
            MaxAge: 3000

  BackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: catch-all/
      Handler: catch-all
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref BackendApi
      Environment:
        Variables:
          STORAGE_BUCKET_NAME: !Ref Storage

Outputs:
  BackendUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  BackendFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt BackendFunction.Arn
  BackendFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt BackendFunctionRole.Arn
