AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend API to store data

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  Storage:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: catch-all/
      Handler: catch-all
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          STORAGE_BUCKET_NAME: !Ref Storage

Outputs:
  BackendAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  BackendFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt BackendFunction.Arn
  BackendFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt BackendFunctionRole.Arn
