AWSTemplateFormatVersion: '2010-09-09'
Description: Tsunmiki Uploader Platform.WebServer depends on Platform.Storages

Parameters:
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  DomainName:
    Type: String

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront Distribution
        Origins:
          - Id: S3Origin
            DomainName: "{{resolve:ssm:/app/tsumiki-uploader/platform/storages/frontend/domain-name}}"
            S3OriginConfig:
              OriginAccessIdentity: "origin-access-identity/cloudfront/{{resolve:ssm:/app/tsumiki-uploader/platform/storages/frontend/oai}}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        Enabled: true

  WebDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Sub "${HostedZoneId}"
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # constant
        DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront Distribution Domain Name
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: CloudFront Distribution ID
