AWSTemplateFormatVersion: '2010-09-09'
Description: Tsunmiki Uploader Platform

Resources:
  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: "{{resolve:ssm:/app/tsumiki-uploader/backend/api/resources/api}}"
      DomainName: "{{resolve:ssm:/app/tsumiki-uploader/platform/api-domain-name}}"
      Stage: Prod
